### TODO#12
### Completa los ... de las siguientes peticiones por orden,
### para probar el API con el plugin REST CLIENT de VsCode

### Create user

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Nacho",
  "email": "nacho@gmail.com",
  "role": "USER",
  "password": "Nacho123456"
}


### Login

POST http://localhost:8080/api/users/me/session
Content-Type: application/json

{
  "email": "nacho@gmail.com",
  "password": "Nacho123456"
}


### Profile

GET http://localhost:8080/api/users/me
Cookie: session=6f09b014-b86d-4e8b-8a89-3a167e759ec6;


